apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress
  template:
    metadata:
      labels:
        app: nginx-ingress
        app.kubernetes.io/name: nginx-ingress
     #annotations:
       #prometheus.io/scrape: "true"
       #prometheus.io/port: "9113"
       #prometheus.io/scheme: http
    spec:
      serviceAccountName: nginx-ingress
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
      - name: regcred # Must match your secret name
      volumes:
      - name: nginx-plus-license
        secret:
          secretName: license-token # Must match your secret name
      - name: nginx-agent-config
        configMap:
          name: nginx-agent-config
      - name: dataplane-key
        secret:
          secretName: nginx-one-key # Your Dataplane Key Secret Name>
          items:
          - key: data-plane-key   # The key inside your k8s secret
            path: dataplane.key
      containers:
      - image: private-registry.nginx.com/nginx-ic/nginx-plus-ingress:5.3.1 # Check on release notes for latest version https://github.com/nginx/kubernetes-ingress/releases
        imagePullPolicy: IfNotPresent
        name: nginx-plus-ingress
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: readiness-port
          containerPort: 8081
        - name: prometheus
          containerPort: 9113
        - name: service-insight
          containerPort: 9114
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
         #limits:
         #  cpu: "1"
         #  memory: "1Gi"
        securityContext:
          allowPrivilegeEscalation: false
#          readOnlyRootFilesystem: true
          runAsUser: 101 #nginx
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        # - name: NGINX_AGENT_SERVER_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: nginx-one-key
        #       key: data-plane-key
        volumeMounts:
        - name: nginx-agent-config
          mountPath: /etc/nginx-agent/nginx-agent.conf
          subPath: nginx-agent.conf
        - name: dataplane-key
          mountPath: /etc/nginx-agent/secrets
        args:
          - -nginx-plus=true
          - -nginx-configmaps=$(POD_NAMESPACE)/nginx-config
          - -mgmt-configmap=$(POD_NAMESPACE)/nginx-config-mgmt
          - -report-ingress-status
          - -external-service=nginx-ingress
          - -nginx-status-allow-cidrs=0.0.0.0/0
          - -agent=true # Enables the NGINX One Agent
         #- -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret
         #- -enable-cert-manager
         #- -enable-external-dns
         #- -enable-app-protect
         #- -enable-app-protect-dos
         #- -log-level=debug # Enables extensive logging. Useful for troubleshooting. Options include: trace, debug, info, warning, error, fatal
         #- -log-format=glog # Sets the log format. Options include: glog, json, text
         #- -enable-prometheus-metrics
         #- -enable-service-insight
         #- -global-configuration=$(POD_NAMESPACE)/nginx-configuration
#      initContainers:
#      - image: nginx/nginx-ingress:5.3.1
#        imagePullPolicy: IfNotPresent
#        name: init-nginx-ingress
#        command: ['cp', '-vdR', '/etc/nginx/.', '/mnt/etc']
#        securityContext:
#          allowPrivilegeEscalation: false
#          readOnlyRootFilesystem: true
#          runAsUser: 101 #nginx
#          runAsNonRoot: true
#          capabilities:
#            drop:
#            - ALL
        